name: Build Fat JAR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

    - name: Build with Maven
      run: chmod +x gradlew && ./gradlew clean shadowJar

    - name: Upload Fat JAR
      uses: actions/upload-artifact@v2
      with:
        name: fat-jar
        path: target/*-with-dependencies.jar
