run-name: Build JAR

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
          distribution: 'temurin'
          java-version: '21'

    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew bootJar

    - name: Upload JAR
      uses: actions/upload-artifact@v4.3.3
      with:
        name: boot-jar
        path: build/libs/*.jar
