name: Build JAR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew bootJar

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: boot-jar
        path: build/libs/*.jar
